import { Router } from "express";
import { healthRouter } from "./health.route";
import { schoolRouter } from "./school.route";
import { authRouter } from "./auth.route";
import { meRouter } from "./me.route";
import { userRouter } from "./user.route";
import { academicSessionRouter } from "./academicSession.route";
import { classRouter } from "./class.route";
import { sectionRouter } from "./section.route";
import { subjectRouter } from "./subject.route";
import { studentRouter } from "./student.route";
import { staffRouter } from "./staff.route";
import { guardianRouter } from "./guardian.route";
import { holidayRouter } from "./holiday.route";
import { attendanceRouter } from "./attendance.route";
import { announcementRouter } from "./announcement.route";
import { leaveRequestRouter } from "./leaveRequest.route";
import { timetableSlotRouter } from "./timetableSlot.route";
import { examRouter, examSubjectRouter } from "./exam.route";
import { assignmentRouter } from "./assignment.route";
import { localUploadRouter } from "./localUpload.route";
import { dashboardRouter } from "./dashboard.route";
import { notificationRouter } from "./notification.route";
import { feeStructureRouter } from "./feeStructure.route";
import { feeInvoiceRouter, feePaymentRouter } from "./feeInvoice.route";
import { documentRouter } from "./document.route";
import { reportsRouter } from "./reports.route";
import { libraryBookRouter } from "./libraryBook.route";
import { bookLoanRouter } from "./bookLoan.route";
import { bookReservationRouter } from "./bookReservation.route";
import { vehicleRouter } from "./vehicle.route";
import { transportRouteRouter } from "./transportRoute.route";
import { studentRouteRouter } from "./studentRoute.route";

export const apiRouter = Router();

apiRouter.use("/health", healthRouter);
apiRouter.use("/schools", schoolRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/me", meRouter);
apiRouter.use("/users", userRouter);
apiRouter.use("/academic-sessions", academicSessionRouter);
apiRouter.use("/classes", classRouter);
apiRouter.use("/sections", sectionRouter);
apiRouter.use("/subjects", subjectRouter);
apiRouter.use("/students", studentRouter);
apiRouter.use("/staff", staffRouter);
apiRouter.use("/guardians", guardianRouter);
apiRouter.use("/holidays", holidayRouter);
apiRouter.use("/attendance", attendanceRouter);
apiRouter.use("/announcements", announcementRouter);
apiRouter.use("/leave-requests", leaveRequestRouter);
apiRouter.use("/timetable-slots", timetableSlotRouter);
apiRouter.use("/exams", examRouter);
apiRouter.use("/exam-subjects", examSubjectRouter);
apiRouter.use("/assignments", assignmentRouter);
apiRouter.use("/uploads/local", localUploadRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/notifications", notificationRouter);
apiRouter.use("/fee-structures", feeStructureRouter);
apiRouter.use("/fee-invoices", feeInvoiceRouter);
apiRouter.use("/fee-payments", feePaymentRouter);
apiRouter.use("/documents", documentRouter);
apiRouter.use("/reports", reportsRouter);
apiRouter.use("/library-books", libraryBookRouter);
apiRouter.use("/book-loans", bookLoanRouter);
apiRouter.use("/book-reservations", bookReservationRouter);
apiRouter.use("/vehicles", vehicleRouter);
apiRouter.use("/routes", transportRouteRouter);
apiRouter.use("/student-routes", studentRouteRouter);
