import { Router } from "express";
import { healthRouter } from "./health.route";
import { schoolRouter } from "./school.route";
import { authRouter } from "./auth.route";
import { meRouter } from "./me.route";
import { academicSessionRouter } from "./academicSession.route";
import { classRouter } from "./class.route";
import { sectionRouter } from "./section.route";
import { subjectRouter } from "./subject.route";
import { studentRouter } from "./student.route";
import { staffRouter } from "./staff.route";
import { guardianRouter } from "./guardian.route";
import { holidayRouter } from "./holiday.route";
import { attendanceRouter } from "./attendance.route";

export const apiRouter = Router();

apiRouter.use("/health", healthRouter);
apiRouter.use("/schools", schoolRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/me", meRouter);
apiRouter.use("/academic-sessions", academicSessionRouter);
apiRouter.use("/classes", classRouter);
apiRouter.use("/sections", sectionRouter);
apiRouter.use("/subjects", subjectRouter);
apiRouter.use("/students", studentRouter);
apiRouter.use("/staff", staffRouter);
apiRouter.use("/guardians", guardianRouter);
apiRouter.use("/holidays", holidayRouter);
apiRouter.use("/attendance", attendanceRouter);
