import { Router } from "express";
import crypto from "node:crypto";
import { HttpError } from "../middleware/errorHandler";
import { readLocalFile, signLocalDownload } from "../lib/storage";

// Dev-only fallback for serving files when R2 isn't configured — see
// lib/storage.ts. Deliberately not behind `authenticate`: this is reached
// via a plain browser navigation (window.open), which carries no
// Authorization header. Access control instead comes from the signed,
// short-lived key+exp+sig query params generated by getDownloadUrl() —
// same shape as a real presigned R2 URL. Never reachable in production
// once R2 env vars are set.
export const localUploadRouter = Router();

localUploadRouter.get("/", async (req, res, next) => {
  try {
    const key = req.query.key as string | undefined;
    const exp = Number(req.query.exp);
    const sig = req.query.sig as string | undefined;
    if (!key || key.includes("..") || !exp || !sig) {
      throw new HttpError(400, "Invalid or missing link parameters");
    }
    if (Date.now() > exp) throw new HttpError(410, "This download link has expired");

    const expected = signLocalDownload(key, exp);
    const sigBuf = Buffer.from(sig);
    const expectedBuf = Buffer.from(expected);
    if (sigBuf.length !== expectedBuf.length || !crypto.timingSafeEqual(sigBuf, expectedBuf)) {
      throw new HttpError(403, "Invalid download link");
    }

    res.sendFile(readLocalFile(key));
  } catch (err) {
    next(err);
  }
});
